# Generated by Django 6.0.1 on 2026-01-12 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
                ('pan', models.CharField(max_length=20)),
                ('qr_channel', models.CharField(choices=[('fonepay', 'Fonepay'), ('nepalpay', 'Nepalpay')], max_length=20)),
                ('agree_deposits', models.BooleanField(default=False)),
                ('agree_pay', models.BooleanField(default=False)),
                ('declare', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=100)),
                ('branch_staff_contact', models.CharField(max_length=50)),
                ('submitter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
            ],
        ),
        migrations.CreateModel(
            name='FormAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.forms')),
            ],
        ),
    ]
