# Generated by Django 6.0.1 on 2026-01-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='branch',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='qr_channel',
            field=models.CharField(blank=True, choices=[('fonepay', 'Fonepay'), ('nepalpay', 'Nepalpay')], max_length=20, null=True),
        ),
    ]
